### ISSUE TITLE
Algo d'explo pas robuste

### ISSUE THREAD

**Issue by LoucIsZbib** [LoucIsZbib/SpaceBaracraftCivilization#13]
Est-ce que parce que tout est visité ? 

`
  File "/home/luc/Projets/SpaceBaracraftCivilization/bot/bot.py", line 195, in play_turn
    destination = self.closest_unvisited_star(ship)
  File "/home/luc/Projets/SpaceBaracraftCivilization/bot/bot.py", line 216, in closest_unvisited_star
    destination = valid_sorted_destination[0]
IndexError: list index out of range
`

**Comment by odoucet** [comment]
tu vérifies pas si `valid_sorted_destination` est bien un tableau avec des entrées. Là tu demandes le premier élément à l'intérieur et Python te dit que raté, cet index n'existe pas (== le tableau est vide).

**Comment by LoucIsZbib** [comment]
la façon de faire a changé : ce ne sont plsu les bots qui cherchent quelle cible, c'est la commande EXPLORE qui est côté moteur de jeu (pour permettre aux joueurs humains féniants de l'utiliser aussi)

https://github.com/LoucIsZbib/SpaceBaracraftCivilization/commit/3645a5f51f2dc0f6bdce95b26027aee92cbcfdb6

L'implémentation a changé : la liste des étoiles ne sera plus jamais vide, car on ne prend pas les étoiles non visitées, on prend toutes les étoiles et elles sont triées par date de visite.
Comme il y a forcément l'étoile de sa colonie principale, la liste ne sera pas vide.
Autre avantage : une fois qu'on a exploré toute la galaxie, on recommence histoire de spotted les colonies des autres :)
