### ISSUE TITLE
MOUVEMENTS - ajouter une commande EXPLORE pour l'explo auto

### ISSUE THREAD

**Issue by LoucIsZbib** [LoucIsZbib/SpaceBaracraftCivilization#9]
Est-ce qu'on définit un type de vaisseau spécial explo ? ou tous les vaisseaux sont concernés par cette commande EXPLORE ?

**Comment by odoucet** [comment]
tous les vaisseaux sont concernés.
Pas de vaisseau spécial explo, le TR1, plus petit vaisseau, fait très bien l'affaire.

**Comment by LoucIsZbib** [comment]
OK, sur FarHorizons, la commande AUTO donne la capacité d'explo auto au TR1 uniquement.

Ici on aura `EXPLORE BF2 Firefly` et cela lancera l'explo pour ce vaisseau, quel que soit son type

**Comment by LoucIsZbib** [comment]
L'ordre d'exploration des systèmes/étoiles sera le suivant : 
1- tri des étoiles par dernière visite, la plus ancienne en premier
2- tri des étoiles par distance, la plus proche en premier

L'idée est de pouvoir boucler sur le tour de la galaxie : dans FH, une fois toutes étoiles visitées, l'explo auto s'arrête. C'est dommage, car si un adversaire construit une colonie juste après, il faudrait pouvoir la scouter. 

Reste maintenant à trouver comment trier des listes selon 2 critères en python :)

**Comment by odoucet** [comment]
https://docs.python.org/fr/3/howto/sorting.html#sort-stability-and-complex-sorts

**Comment by LoucIsZbib** [comment]
> https://docs.python.org/fr/3/howto/sorting.html#sort-stability-and-complex-sorts

MAGIQUE !

**Comment by LoucIsZbib** [comment]
Et voilà ! https://github.com/LoucIsZbib/SpaceBaracraftCivilization/commit/3645a5f51f2dc0f6bdce95b26027aee92cbcfdb6
double tri : d'abord on privilégie les étoiles dont la visite est la plus ancienne, et en cas d'égalité on prend la plus proche. 
Normalement la même étoile ne peut être visée 2 fois dans le même tour, mais j'ai pas testé particulièrement ce point
